### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by vladershoff** [umbrik/wtAutosaver#4]
Привет, может есть смысл собрать файл webtutorConnector.js в виде npm пакета. Было бы удобно в дальнейшем использовать его на других проектах через npm install.

**Comment by umbrik** [comment]
> Привет, может есть смысл собрать файл webtutorConnector.js в виде npm пакета. Было бы удобно в дальнейшем использовать его на других проектах через npm install.

ok

**Comment by umbrik** [comment]
> Привет, может есть смысл собрать файл webtutorConnector.js в виде npm пакета. Было бы удобно в дальнейшем использовать его на других проектах через npm install.

https://github.com/umbrik/webtutor-connector
